### ISSUE TITLE
Does not work without doctype

### ISSUE THREAD

**Issue by xealot** [VFK/gulp-html-replace#16]
I had to add `<!DOCTYPE html>` to my html to get this module not completely wang the output. This seems like a bug.

**Comment by VFK** [comment]
It's been awhile, and looks like you don't want to talk :) Anyway, with the recent fixes maybe this issue is not an issue anymore. I'm closing this issue, but feel free to open another one if you still have this problem with the latest version.

**Comment by xealot** [comment]
Aye sorry, I lost track of this. Yeah... closed for now sounds good to me.
