### ISSUE TITLE
Replace fails in file with mixed line endings

### ISSUE THREAD

**Issue by ghost23** [VFK/gulp-html-replace#22]
Hi,

when I have a file, that generally has LF line endings, but for some reason, there
are also some CRLF line endings, then htmlreplace does not replace anything in the file.

**Comment by VFK** [comment]
Ugh line endings again... Could you please provide this odd file so i can fix it once and for all?

**Comment by ghost23** [comment]
Sure,

how should I do that? It seems, i cannot attach it here.

**Comment by bmacnaughton** [comment]
Would splitting lines based on \n only (completely ignore \r) be the right approach here? If you do that the \r, if it's present, would just be part of the line. And you can handle any mixture of \n or \r\n lines. I don't think there is any need to actually test for \r\n.

**Comment by VFK** [comment]
@ghost23 Maybe Dropbox, Google Drive worked pretty well in this comment too: https://github.com/VFK/gulp-html-replace/issues/19#issuecomment-69750870 Any file sharing thing basically. Thank you.

@bmacnaughton It might work, but there may be some weird problems in rare cases. I better look at that file and run some tests before i do anything about it.

**Comment by ghost23** [comment]
That makes sense  :)
https://www.dropbox.com/s/s5sej5grjr1fccv/line_endings-html.html?dl=0

**Comment by bmacnaughton** [comment]
I think it works OK but you do have to make a decision on line 26 about what linefeed sequence to insert.

It wouldn't handle OLD Mac files with a \r line separator, but I don't think that really matters any longer.

**Comment by VFK** [comment]
@bmacnaughton  I'm using split by \n, this seems to be working ok, thanks for the idea. I think i better modify the code to not do "split" at all, but this is something for the future releases.

@ghost23, @charlescaron i've added your files to the ["test" folder](https://github.com/VFK/gulp-html-replace/tree/master/test/line_endings). I couldn't ask for a permission, there is no such thing as private messages on github, but if you're not ok with this (maybe those files are from some super-secret project or something) then please open an issue and i'll remove them.

**Comment by bmacnaughton** [comment]
Thanks for the note. I think you're right - no split at all would be better but that's a bigger change. The history of line endings still makes life complicated.
