### ISSUE TITLE
How can I include all js files in folder and subfolders?

### ISSUE THREAD

**Issue by paveliko** [VFK/gulp-html-replace#24]
Hey,

I tring to include all js files in folder and subfolders.
htmlreplace({
            js: {
                src: '/dir/**/*.js',
                tpl: '<script src="%s"></script>'
            }
        })

What the way to do that?

Thanks,
Pavel

**Comment by VFK** [comment]
Hi Pavel. Try to use [resolvePaths](https://github.com/VFK/gulp-html-replace#options) option and tell me if you see what you want to see. Like so:
```javascript
htmlreplace({
  js: {
    src: '/dir/*/.js',
    tpl: ''
  }
}, {resolvePaths: true})
```

**Comment by VFK** [comment]
Hi Pavel. This module doesn't perform any filesystem operations, so for now you need to use other modules which returns a list of files. Try to look at my response at similar question [here](https://github.com/VFK/gulp-html-replace/issues/3#issuecomment-38352524). You may probably need to play with options of glob module depending on what you want to see as src path. There is also [resolvePaths](https://github.com/VFK/gulp-html-replace#options) option which may help you to resolve paths relative to your html file.

**Comment by paveliko** [comment]
Geat! It's good enough for me :) Thanks Vladimir.
