### ISSUE TITLE
Resolving relative paths question

### ISSUE THREAD

**Issue by Pouja** [VFK/gulp-html-replace#31]
I have bunch of html pages which have 1 or more link tags. Im not sure from you readme if the following situation is possible with your plugin:
```
<link rel="stylesheet" href="dist/css/style.css/>
<link rel="stylesheet" href="dist/css/style2.css/>
```
to
```
<link rel="stylesheet" href="css/style.css/>
<link rel="stylesheet" href="css/style2.css/>```

**Comment by VFK** [comment]
@Pouja Looks like i totally missed that question, i'm very sorry. This is probably doesn't matter by now, but i'll answer anyway. If you want to actually change the path, like take "dist/css/style.css" and turn it into "css/style.css" by removing "dist/" then no, this plugin does not perform any operation on strings being replaced. It just cuts everything between the tags and put whatever you want instead. However if you know what the replacement result should be, like if you have an array like this: "['css/style.css', 'css/style2.css']" then yes, you can pass it to the plugin and it'll create tags and replace the old links.

**Comment by Pouja** [comment]
@VFK Oke thanks for the info!
