### ISSUE TITLE
"Like useref but done right" details?

### ISSUE THREAD

**Issue by zckrs** [VFK/gulp-html-replace#33]
Hi @VFK,
I use gulp-useref in projects (like https://github.com/Swiip/generator-gulp-angular) and I am not totally happy. 
I think migrate to your gulp-html-replace

But can you expose why your plugin is better?

**Comment by VFK** [comment]
Hello @zckrs 
I just realized how mean this "Like useref but done right" sounds :smile:  I did not want to mock other's people work of course, just wanted to explain in fewer words what this plugin does. The main difference is basically in the way these plugins configured. With useref you specify everything in your template which i think is really bad idea. gulp-html-replace is configured through the code. 

For example this is useref html:
```html
<head>
    <!-- build:css css/combined.css -->
    <link href="css/one.css" rel="stylesheet">
    <link href="css/two.css" rel="stylesheet">
    <!-- endbuild -->
</head>
```
And you do in your gulpfile:
```javascript
gulp.src('src/index.html')
        .pipe(useref())
        .pipe(gulp.dest('dist'));
```

This is how you do the same with gulp-html-replace:
```html
<head>
    <!-- build:css -->
    <link href="css/one.css" rel="stylesheet">
    <link href="css/two.css" rel="stylesheet">
    <!-- endbuild -->
</head>
```

gulpfile:
```javascript
gulp.src('src/index.html')
    .pipe(htmlreplace({'css': 'css/combined.css'}))
    .pipe(gulp.dest('dist'));
```

See the difference? You specify the replacement in the code, not in the html. This way your code more flexible. What if you don't know what will the replacement be? Like if it comes from somewhere else or being calculated on the fly? How do you specify in html something you don't know yet? Basically you separate logic and presentation, this is what "Like useref but done right" means. And also this plugin provides more advanced replacements but you better check the docs or you can just explain what is you trying to achieve and i'll tell you if it's possible with this plugin.

**Comment by zckrs** [comment]
Thank you for this response. 

In fact we use the alternate search path option in gulp-useref and I don't find this option in your plugin.

```
<!-- build:<type>(alternate search path) <path> -->
... HTML Markup, list of script / link tags.
<!-- endbuild -->
```

Do you have a solution =\ ?

**Comment by VFK** [comment]
@zckrs I checked out useref docs and i'm not really sure what the output with "alternate search path" option should be. Does it changes paths for links between the build tags? If this is the case then you may look at my answer here: https://github.com/VFK/gulp-html-replace/issues/31 Or does it replace everything between the build tags with the links from somewhere else? In this case maybe you can use this solution:  https://github.com/VFK/gulp-html-replace/issues/3#issuecomment-38352524 If this is something about resolving paths then this plugin has the option to [resolvePaths](https://github.com/VFK/gulp-html-replace#options).

**Comment by robwierzbowski** [comment]
I don't think the alternate search path option is necessary here. GHR doesn't process or automatically read referenced files; it only changes strings in the HTML, so there's no need to read js or css files off of disk.

Pseudo task with cache hash:

```js
  const jsMap = require('./dist/scripts/rev-manifest');
  const cssMap = require('./dist/styles/rev-manifest');

  return gulp.src('app/index.jade')
  .pipe($.jade())
  .pipe($.htmlReplace({
      js: `/scripts/${jsMap["main.js"]}`,
      css: `/styles/${cssMap["main.css"]}`
    })
    .pipe(gulp.dest('dist'))
```

where the manifests are created by gulp-rev in previous styles and scripts tasks.

**Comment by laicosly** [comment]
useref pipes the files in the <build> tag so that you can transmute them, which this project does not seem to do.  they both seem like different approaches, and I wouldn't say one or the other is "right"
