### ISSUE TITLE
When keepUnassigned = true, comments are remove?

### ISSUE THREAD

**Issue by bretkikehara** [VFK/gulp-html-replace#37]
I would like to run htmlReplace twice rather than once. After the first run, it seems like the comments are removed https://github.com/VFK/gulp-html-replace/blob/549aaaacbff7549437e2df6de30a6c3a05f13933/lib/block.js#L24.

Let me your thoughts and I am willing to make a PR.

#### tldr; I am trying to avoid this for 1st htmlReplace run:
```
htmlReplace({
    config: {
        src: '',
        tpl: '<!-- build:config --><!-- endbuild -->'
    }
})
```

**Comment by VFK** [comment]
@bretkikehara Hi. There is also the option [keepBlockTags](https://github.com/VFK/gulp-html-replace#options) which should left comments intact. Could you please try with it set to `true`? Like so: `{keepUnassigned: true, keepBlockTags: true}`

**Comment by bretkikehara** [comment]
Thank you for the quick reply.

After your comment, I thought about it some more. Since it doesn't matter whether the tags are preserved during the 1st pass, set options as `{keepUnassigned: true, keepBlockTags: true}`. Then on 2nd pass, set options as `{keepUnassigned: true}`.

#### Solution
###### 1st pass
```
htmlReplace({
     js: [ ... ],
     css: [ ... ],
     options: {
         keepUnassigned: true,
         keepBlockTags: true
     }
});
```

###### 2nd pass
```
htmlReplace({
    config: {
        src: fs.readFileSync('path/to/config.js'),
        tpl: '<script>%s</script>'
    },
    options: {
         keepUnassigned: true,
    }
});
