### ISSUE TITLE
Incorrectly deleting build blocks

### ISSUE THREAD

**Issue by burt202** [VFK/gulp-html-replace#40]
Hi, so I have the following gulpfile:

    var gulp = require("gulp");
    var htmlreplace = require("gulp-html-replace");

    gulp.task("build", function () {
      return gulp.src("test.html")
        .pipe(htmlreplace({
          "test-content": ""
        }))
        .pipe(gulp.dest("dist"));
    });

and this html file:

    <html>
    <body>
      main content

      
        test content here
      

      
        prod content here
      
    </body>
    </html>

when i run the gulp task i get the following....

    <html>
    <body>
      main content

      

    </body>
    </html>

....the content within the "build:prod-content" block is being removed as well even though i have not asked the gulp task to touch it. Why is this happening and is there a way around this?

Im using v1.5.4, gulp v3.9.0

Many thanks

**Comment by VFK** [comment]
Hi @burt202 sorry for the delay. Please looks at [options](https://github.com/VFK/gulp-html-replace#options), there is the option called "keepUnassigned", with it set to "true" this plugin won't touch blocks if their name is not in config. Try something like this: `htmlreplace({"test-content": ""}, {"keepUnassigned": false})`. There is also the way to keep comments in such blocks (the "" ones), the option for this is "keepBlockTags"

**Comment by burt202** [comment]
Apologies. Totally missed this. Many thanks
